Newscoop\Entity\Author:
    exclusion_policy: ALL
    exclude: false
    properties:
        biography:
            expose: true
            read_only: true
            type: string
            serialized_name: biography
            access_type: public_method
        first_name:
            expose: true
            type: string
            serialized_name: firstName
        last_name:
            expose: true
            read_only: true
            type: string
            serialized_name: lastName
        image:
            expose: true
            read_only: true
            type: image_uri
            serialized_name: image
            accessor: 
                getter: getView
