Newscoop\Entity\Section:
    exclusion_policy: ALL
    properties:
        number:
            expose: true
            read_only: true
            type: integer
            groups: ["list"]
            serialized_name: number
        name:
            expose: true
            read_only: true
            type: string
            groups: ["list"]
            serialized_name: title
        articlesLink:
            expose: true
            read_only: true
            type: articles_link
            groups: ["list"]
            serialized_name: articlesLink