services:
    comment_notification:
        class:      Newscoop\Services\CommentNotificationService
        arguments:  ["@email", "@comment", "@user"]
        tags:
            -  { name: kernel.event_listener, event: comment.create, method: update }