services:
    user_points:
        class:      Newscoop\Services\UserPointsService
        arguments:  ["@em"]
        tags:
            -  { name: kernel.event_listener, event: image.published, method: update }